#!/bin/bash
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** SIMPLE EXAMPLE (kernel) ***"
echo "Press <enter> to load modules:"
read junk
./ldmod
echo
echo "Now start the realtime process <enter>, <enter> again to end it."
read junk
sync
if (`rtai-config --linux-version | grep -q 3.8`);
then insmod ./rt_oscillator.ko;
else insmod ./oscillator.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
